language: python

python: 3.5

install:
  travis_retry pip install tox

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=coverage

script:
  - tox -e $TOXENV

sudo: false

matrix:
  fast_finish: true
